project_name: aws-assume-role
builds:
  -
    main: dummy.go
    targets:
      - linux_amd64_v1
      - darwin_amd64_v1
      - windows_amd64_v1
      - darwin_arm64
    binary: aws-assume-role
    hooks:
      post: ./copy-packages.sh
archives:
  - id: default
    format: binary
checksum:
  name_template: 'checksums.txt'
release:
  disable: false
