plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/github"
    - assets: 
      - path: target/aws-assume-role_darwin_amd64
      - path: target/aws-assume-role_darwin_arm64
      - path: target/aws-assume-role_windows_amd64.exe
      - path: target/aws-assume-role_linux_amd64
